// <auto-generated />
using System;
using FranDanBackend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FranDanBackend.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20260526231014_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FranDanBackend.Models.Friendship", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("accepted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("blacklisted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("friend1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("friend2Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("friend1Id");

                    b.HasIndex("friend2Id");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("FranDanBackend.Models.Participation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("accepted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("admin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("planId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("planId");

                    b.HasIndex("userId");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("FranDanBackend.Models.Plan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("admininstratorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("admininstratorId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("FranDanBackend.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("emailNotifications")
                        .HasColumnType("INTEGER")
                        .HasColumnName("email_notifications");

                    b.Property<string>("occupation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("verifierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("verifierId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FranDanBackend.Models.Verifier", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("verified")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Verifiers");
                });

            modelBuilder.Entity("FranDanBackend.Models.Friendship", b =>
                {
                    b.HasOne("FranDanBackend.Models.User", "friend1")
                        .WithMany()
                        .HasForeignKey("friend1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FranDanBackend.Models.User", "friend2")
                        .WithMany()
                        .HasForeignKey("friend2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("friend1");

                    b.Navigation("friend2");
                });

            modelBuilder.Entity("FranDanBackend.Models.Participation", b =>
                {
                    b.HasOne("FranDanBackend.Models.Plan", "plan")
                        .WithMany()
                        .HasForeignKey("planId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FranDanBackend.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("plan");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FranDanBackend.Models.Plan", b =>
                {
                    b.HasOne("FranDanBackend.Models.User", "creator")
                        .WithMany()
                        .HasForeignKey("admininstratorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("creator");
                });

            modelBuilder.Entity("FranDanBackend.Models.User", b =>
                {
                    b.HasOne("FranDanBackend.Models.Verifier", "verifier")
                        .WithMany()
                        .HasForeignKey("verifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("verifier");
                });
#pragma warning restore 612, 618
        }
    }
}
